# name of the program (Minix service)
PROG=proj

.PATH: ${.CURDIR}/device_controllers
.PATH: ${.CURDIR}/device_controllers/timer
.PATH: ${.CURDIR}/device_controllers/kbc

# source code files to be compiled
SRCS = proj.c timer.c kbc.c utils.c

# additional compilation flags
# "-Wall -Wextra -Werror -I . -std=c11 -Wno-unused-parameter" are already set
CFLAGS += -pedantic
CPPFLAGS += -pedantic

# list of library dependencies (for Lab 2, only LCF library)
DPADD += ${LIBLCF}
LDADD += -llcf 

# include LCOM's makefile that does all the "heavy lifting"
.include <minix.lcom.mk>
